all:
	gcc stack/src/simple-calculator.c ../stack/stack.c -o stack/bin/simple-calculator
	gcc stack/src/text-editor.c ../stack/stack.c -o stack/bin/text-editor
	gcc stack/src/array-recursive-stack.c -o stack/bin/array-recursive-stack
	gcc stack/src/linked-list-recursive-stack.c -o stack/bin/linked-list-recursive-stack
